import { mkChecklist } from './checklist.js';

const SECTION_ORDER = [
  'demographics','presenting_concerns','self_help','daily_living',
  'safety','communication','self_stim','medical_necessity',
  'behavior_targets','skill_acquisitions','crisis_plan',
];

const SECTION_TITLES = {
  demographics:'Demographics & Referral Info',
  presenting_concerns:'Presenting Concerns',
  self_help:'Self-Help Skills',
  daily_living:'Daily Living Skills',
  safety:'Safety Concerns',
  communication:'Communication',
  self_stim:'Self-Stimulatory Behavior',
  medical_necessity:'Medical Necessity',
  skill_acquisitions:'Skill Acquisitions',
  behavior_targets:'Behavior Targets',
  crisis_plan:'Crisis Plan',
};

const makeSections = () => Object.fromEntries(
  SECTION_ORDER.map(key => [key, {
    key,
    title: SECTION_TITLES[key],
    completionState: 'empty',
    notes: '',
    indicators: key === 'behavior_targets' ? [
      { id:'ant-demand',      label:'Antecedent: Demand placed',         count:0, isCustom:false, unit:'tag' },
      { id:'ant-transition',  label:'Antecedent: Transition',            count:0, isCustom:false, unit:'tag' },
      { id:'ant-attention',   label:'Antecedent: Attention withdrawn',   count:0, isCustom:false, unit:'tag' },
    ] : [],
    skillGoals: [],
    behaviorTargets: [],
    recordingState: 'idle',
    recordingDurationSeconds: 0,
    transcript: null,
    transcriptFlagged: false,
    hasConflict: false,
    draftContent: null,
    aiOriginalContent: null,
    draftState: 'blank',
    approvalState: 'pending',
    lastSavedAt: null,
  }])
);

export const makeAssessmentSession = (clientId, clientName, bcbaId, bcbaName) => ({
  id: `session_${clientId}_${Date.now()}`,
  clientId, clientName, bcbaId, bcbaName,
  status: 'not_started',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  consentGranted: false,
  consentGrantedAt: null,
  sectionsWithData: 0,
  totalInterviewSections: 10,
  sectionsApproved: 0,
  clientProfile: {
    dob: '', phone: '', address: '', referralDate: '',
    insurerName: '', memberId: '', groupNumber: '', referringProvider: '',
    diagnosis: '', gender: '', icd10: '', medicaidId: '',
    assessmentType: 'Initial', assessmentDate: '',
    parentGuardianNames: '', relationship: '', preferredLanguage: 'English',
    reasonForReferral: '', interventionSettings: [],
  },
  sections: makeSections(),
  result: null,
});

// ─── Mock interview data — pre-filled demo sessions ──────────────────────────

function makeFilledSession(clientId, clientName, bcbaId, bcbaName, sectionData, profileOverrides = {}) {
  const base     = makeAssessmentSession(clientId, clientName, bcbaId, bcbaName);
  const sections = { ...base.sections };

  for (const [key, data] of Object.entries(sectionData)) {
    sections[key] = {
      ...sections[key],
      ...data,                                    // spread ALL seed fields — future-proof
      notes:           data.notes           ?? '',// keep null-safe defaults for critical fields
      transcript:      data.transcript      ?? null,
      completionState: data.completionState ?? 'partial',
    };
  }

  const sectionsWithData = Object.values(sections).filter(
    s => s.key !== 'demographics' && s.completionState !== 'empty',
  ).length;

  return {
    ...base,
    id:               `session_${clientId}_demo`,
    consentGranted:   true,
    consentGrantedAt: '2026-05-20T10:15:00Z',
    status:           'in_progress',
    sectionsWithData,
    sectionsApproved: 0,
    updatedAt:        '2026-05-22T14:30:00Z',
    sections,
    clientProfile:    { ...base.clientProfile, ...profileOverrides },
  };
}

// ── Emma Thompson mock data ──────────────────────────────────────────────────

const EMMA_INTERVIEW_DATA = {
  demographics: {
    notes: 'Emma Thompson, DOB 01/30/2020 (age 6). Dx: ASD Level 3 (Dr. Robert Chen, Dev Peds, 03/2024 — ADOS-2 Module 1, ADI-R, Vineland-3). Insurance: Humana HUM-334490 / G-98712. Lives with both parents + older brother (age 9, NT). Primary language: English. School: Palm Academy, Boca Raton — Kindergarten with 1:1 aide under IEP. SLP 2x/week, OT 1x/week. No prior ABA.',
    completionState: 'complete',
  },
  presenting_concerns: {
    notes: 'Family top concerns: (1) Very limited verbal communication — 8-10 single words used inconsistently, no functional requesting. Uses hand-leading and pointing only. (2) Head banging on hard surfaces 4-8x/day, primarily during transitions and demand presentation. Marks observed; no medical attention needed yet. Parents frightened about escalation. (3) Severe food selectivity — 6 accepted foods only (see self-help). School reports 1 documented peer hitting incident (last week, first time). Family considering more restrictive school placement if no improvement.',
    transcript: "Mom: She still isn't talking to tell us what she needs. She has a few words but she doesn't use them. She just gets frustrated and starts hitting her head on the wall. It happens the most when we try to take something away or ask her to do something she doesn't like. We put padding on the wall in her room. Dad: The school called this week — she hit another kid during free play, which she's never done before. That was a shock. And the feeding is another huge issue. She literally only eats six foods. If we put anything else on her plate she has a complete meltdown.",
    completionState: 'complete',
  },
  self_help: {
    notes: 'Toileting: urinary trained daytime (1-2 accidents/week). Bowel NOT trained — full-time pull-ups. No self-initiation; scheduled toileting every 90 min. Cannot manage clothing during toileting independently. Dressing: full physical assistance for upper body; steps into pants with verbal prompt. No fasteners managed. Tactile sensitivity: seamless socks + tagless shirts required — meltdown if seamed clothing applied. Feeding: 6 accepted foods only — chicken nuggets (specific brand), white rice, plain crackers, apple juice, vanilla wafer cookies, peeled apple slices. No utensils — finger eating. OT feeding eval March 2024: sensory-based avoidance confirmed.',
    completionState: 'partial',
  },
  daily_living: {
    notes: 'Morning routine: fully dependent — all steps require physical prompting. No visual schedule at home (school uses one). Bedtime: semi-structured — bath attempt (often refused), PJs, 30 min tablet, lights out. Takes 60-90 min. Sleep onset generally OK once in bed. Transitions: 70% result in behavioral escalation (head banging or tantrum). Community: avoids grocery stores, restaurants, loud public spaces. Playground tolerated 10-15 min. No chores currently. Leisure: very strong preference for iPad (water videos, satisfying/sensory content on YouTube). Spins objects independently 20-30 min. Independent play: 15-20 min with light-up/spinning toys.',
    completionState: 'partial',
  },
  safety: {
    notes: 'SIB (Head banging): 4-8 episodes/day. Surfaces: walls, floor, occasionally caregiver shoulder. Visible marks observed post-episode; no medical treatment needed. Parents have installed foam padding in bedroom and hallway. Elopement: no history. No water body access (no home pool, backyard fenced). Aggression toward others: school incident (1x hitting peer during free play). No home aggression toward persons currently. Minimal property destruction (knocking over items, not sustained). No law enforcement involvement.',
    transcript: "She bangs her head mostly when we remove something she's enjoying or ask her to transition. The wall in her room — she's done it so many times we put padding up there. We don't have a pool, backyard is fenced. There was one incident at school where she hit another kid but there's no aggression at home toward people. The head banging is the main safety concern for us right now.",
    completionState: 'partial',
    riskLevel: 'High',
    sibPresent: true,
    sibTopography: ['Head banging'],
    sibFrequency: '6',
    sibInjuryHistory: true,
    sibInjuryNotes: 'Visible marks/redness observed post-episode on forehead. No medical treatment required to date. Parents have installed foam padding on bedroom and hallway walls as protective measure.',
    aggressionPresent: true,
    aggressionTopography: ['Open-hand hitting'],
    aggressionTargets: ['Peers'],
    aggressionFrequency: '0',
    aggressionInjuryHistory: false,
    aggressionInjuryNotes: '1 documented incident at school (peer hitting during free play). No injuries reported. First occurrence — no prior home aggression toward persons.',
    elopementPresent: false,
    propertyDestructionPresent: true,
    propertyDestructionNotes: 'Minimal — occasional knocking over of small items. Not sustained or targeted. No significant property damage.',
    envSafety: [
      'Pool / water body secured or no access',
      'Firearms secured or not present',
      'Padding / protective equipment installed',
    ],
    lawEnforcementInvolvement: false,
    hospitalizationHistory: false,
  },
  communication: {
    notes: 'Primarily nonverbal. ~8-10 single words inconsistently (more, no, mama, done, up, ball, go most reliable). No functional requesting with words — uses hand-leading, pointing, reaching. PECS Phase 2 at school (single exchange, prompted). AAC trial started 2 weeks ago (Proloquo2Go, school SLP-led). Receptive: name response ~60% familiar adults. Follows single-step instructions in familiar contexts (sit, come here, give me). Two-step not followed. No consistent yes/no. Identifies some body parts on self. Eye contact limited but improves with preferred items. No reciprocal social communication. No peer-directed communication observed.',
    transcript: "She doesn't talk to tell us things. She takes our hand and pulls us to what she wants or she'll point. At school they do PECS and she can hand the card when prompted but she doesn't go get the card herself. The iPad app is very new — the SLP just started it. We don't really know how to use it at home yet.",
    completionState: 'complete',
    primaryCommunicationModes: ['PECS', 'AAC Device', 'Gestural / Pointing'],
    aacSystem: 'Proloquo2Go',
    aacPhase: 'Trial phase — 2 weeks in, school SLP-led. No independent symbol activation yet; full physical prompt required.',
    pecsPhase: 'II',
    functionalRepertoire: ['Requesting preferred items/activities', 'Protesting / refusing'],
    receptiveSingleStep: '60',
    receptiveTwoStep: '0',
    receptiveMultiStep: false,
    eyeContact: 'Limited',
    initiatesCommunication: 'Rarely',
    turnTaking: 'Absent',
    slpServices: true,
    slpFrequencyPerWeek: '2',
    slpFocus: 'PECS advancement, AAC introduction, functional communication',
  },
  self_stim: {
    notes: 'Object spinning: highest frequency — bottle caps, coins, lids. Can spin continuously 20-30 min. All settings. Mouthing: mouths clothing, toys, non-food objects. School chew necklace in place. Hand flapping: bilateral, during excitement and transitions. Rocking: front-to-back while seated, especially during screen time. Visual fixation: ceiling fans, moving lights, reflective surfaces. All behaviors high-frequency, cross-setting. OT eval: significant sensory seeking — proprioceptive and vestibular. No sensory diet currently in place at home.',
    completionState: 'partial',
  },
  medical_necessity: {
    notes: 'Dx: ASD Level 3 F84.0 — Dr. Robert Chen, Palm Beach Children\'s Hospital Developmental Peds, March 2024. No secondary diagnoses. No current medications. Pediatrician: Dr. Sarah Mills (last visit April 2026, scheduled follow-up September 2026). Emma requires full physical assistance or 1:1 prompting for virtually all ADLs. No functional communication. Daily SIB. Severe food restriction limiting nutritional variety and community participation. 1 peer aggression incident at school. IEP team discussing placement change for fall. Prior non-ABA interventions: SLP (ongoing), OT (ongoing) — insufficient to address behavioral and communication deficits. Recommended intensity: 30 hrs/week center-based + parent training.',
    transcript: "Mom: The diagnosis was March 2024. Dr. Robert Chen at Palm Beach Children's Hospital — he did the full evaluation, the ADOS and the adaptive testing. He diagnosed her with autism Level 3. Our pediatrician Dr. Mills has been recommending ABA since the diagnosis came back. We started with the SLP and OT first because those were already in place through the school. But after a full year of SLP and OT, she still has no functional communication and the behaviors have gotten worse. Dr. Mills made the referral herself. She said SLP and OT alone aren't enough for Emma's level of need and that ABA is the appropriate next level of care. We don't have her on any medications — Dr. Chen said he wants to try behavioral intervention first before considering anything else.",
    completionState: 'complete',
    coOccurringDiagnoses: [],
    medications: [],
    hasPriorABA: false,
    priorABAHistory: [],
    recommendedHoursPerWeek: '30',
    recommendedSetting: 'Center-based',
  },
  skill_acquisitions: {
    notes: 'Family priority targets: (1) Functional requesting — any modality (PECS, AAC, verbal approximation); (2) receptive labeling — objects and pictures; (3) gross motor imitation. School goals: matching identical objects, simple sorting by color/shape. Reinforcer assessment: light-up spinning toys, iPad (water/sensory videos), vanilla wafers, tickle play, vestibular (spinning in chair). Strong preference hierarchy identified. Attending: brief (1-2 min) with high-preference reinforcers. Accepts reinforcers from familiar adults. DTT naive at home; limited exposure at school. Imitation prerequisite: motor imitation emerging (copies large movements with physical prompt).',
    completionState: 'complete',
    skillGoals: [
      {
        id: 'eg1',
        targetSkill: 'Functional Requesting (Mand Training)',
        operationalDefinition: 'Emma independently selects and exchanges a PECS card or activates an AAC symbol to request a preferred item or activity within 10 seconds of access opportunity, without physical prompt.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Discrete Trial Training (DTT)', 'Natural Environment Teaching (NET)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Partial Physical', promptingLevelCombination: '',
        baselinePercent: '5', baselineOpportunities: '20',
        baselinePromptingDesc: 'Full physical / hand-over-hand required for all exchanges; 1 of 20 opportunities independent',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '3',
        masteryCriteriaSettings: 'Home + school (minimum 2 settings)',
        masteryCriteriaPrompting: 'Independent — no physical or gestural prompt',
        generalizationNotes: 'Across 3 communication partners, 2 settings, minimum 5 different preferred items. Priority probe contexts: item removal (Head Banging antecedent) and transition onset (Tantrum/Drop antecedent) — mastery of requesting "break" and "all done" in these exact contexts is the primary behavior-reduction mechanism for both behavior targets.',
      },
      {
        id: 'eg2',
        targetSkill: 'Receptive Object Labeling',
        operationalDefinition: 'Emma selects the correct object or picture from an array of 3 when given the verbal label (e.g., "touch ball") within 5 seconds, without additional prompting.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Discrete Trial Training (DTT)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Gestural', promptingLevelCombination: '',
        baselinePercent: '20', baselineOpportunities: '30',
        baselinePromptingDesc: 'Gestural prompt to correct item required for ~80% of trials; selects correctly 20% independently',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '3',
        masteryCriteriaSettings: 'Therapy table + natural environment',
        masteryCriteriaPrompting: 'Independent — no gestural or vocal prompt',
        generalizationNotes: 'Probe with novel objects across categories (food, toys, clothing) and with 2 additional trainers',
      },
      {
        id: 'eg3',
        targetSkill: 'Gross Motor Imitation',
        operationalDefinition: 'Emma imitates a gross motor action modeled by the therapist (e.g., clap hands, arms up, stomp feet) within 5 seconds of the verbal cue "do this," without additional prompting.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Discrete Trial Training (DTT)', 'Video Modeling'],
        teachingStrategiesOther: '',
        promptingLevel: 'Full Physical', promptingLevelCombination: '',
        baselinePercent: '15', baselineOpportunities: '20',
        baselinePromptingDesc: 'Full physical prompt required for most actions; 2-3 actions emerging with partial physical only',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '3',
        masteryCriteriaSettings: 'Clinic + home',
        masteryCriteriaPrompting: 'Independent — verbal cue only, no physical or gestural',
        generalizationNotes: 'Generalize to novel motor actions across 2 therapists and in natural group play contexts',
      },
      {
        id: 'eg4',
        targetSkill: 'Matching Identical Objects',
        operationalDefinition: 'Emma places an object onto its identical match from a field of 3 when instructed "match" within 5 seconds, without prompting.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Discrete Trial Training (DTT)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Gestural', promptingLevelCombination: '',
        baselinePercent: '30', baselineOpportunities: '20',
        baselinePromptingDesc: 'Gestural prompt to correct position required; selects correctly ~30% independently',
        masteryCriteriaPercent: '90', masteryCriteriaSessions: '3',
        masteryCriteriaSettings: 'Table — varied array sizes (3 to 5 items)',
        masteryCriteriaPrompting: 'Independent',
        generalizationNotes: 'Generalize to non-identical pictures, then object-to-picture matching in varied locations',
      },
      {
        id: 'eg5',
        targetSkill: 'Transition Tolerance (First-Then Compliance)',
        operationalDefinition: 'Emma transitions from a preferred activity to a non-preferred activity within 60 seconds of a transition cue (verbal + First-Then visual), without engaging in head banging or tantrum/drop behavior, when given a 1-minute countdown and a First-Then visual.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Natural Environment Teaching (NET)', 'Task Analysis / Chaining'],
        teachingStrategiesOther: '',
        promptingLevel: 'Gestural', promptingLevelCombination: '',
        baselinePercent: '10', baselineOpportunities: '20',
        baselinePromptingDesc: 'Transitions result in head banging or tantrum/drop approximately 90% of the time; successful transition requires full verbal + gestural + physical prompt chain',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '5',
        masteryCriteriaSettings: 'Home + school, with familiar and unfamiliar adults',
        masteryCriteriaPrompting: 'First-Then visual cue only — no additional verbal or physical prompt',
        generalizationNotes: 'Priority transition probes: iPad → meal, play → departure, preferred toy → bath. Reduction in Tantrum/Drop and Head Banging behavior targets during transition periods serves as direct generalization measure. Coordinate with OT re: proprioceptive heavy work prior to high-risk transitions to reduce sensory-automatic component of SIB.',
      },
    ],
  },
  behavior_targets: {
    notes: 'Target 1: Head banging (SIB). Topography: forceful head-to-surface contact. Frequency: 4-8x/day. Duration: brief (<10 sec/episode). Ant: item removal, activity transitions, demand presentation, waiting. Function: automatic (sensory) + escape (demand). No prior BIP. Target 2: Tantrum/drop (transition-related). Topography: crying, screaming, going limp on floor, refusing to move. Frequency: 3-5x/day. Duration: 5-20 min. Ant: leaving preferred activity, departure cues. Function: escape from transition demands + access to preferred. Family responses: ignore, redirection, offering preferred item — inconsistent outcomes. No formal FBA completed.',
    transcript: "The head banging is our biggest fear. It's when she doesn't want to stop doing something or when we're asking her to do something she doesn't want to do. Lately it's also happening at what feels like random times and we're not always sure what caused it. The dropping — that's when we need to go somewhere, she just goes limp and won't walk. If we try to pick her up during that it makes everything worse.",
    completionState: 'complete',
    behaviorTargets: [
      {
        id: 'bt-emma-1',
        behaviorName: 'Head Banging (SIB)',
        operationalDefinition: 'Emma forcefully contacts her head against a hard surface (floor, wall, table) with sufficient force to produce an audible sound. Each contact counts as one instance.',
        topography: ['Head banging'],
        frequencyPerDay: '6', frequencyUnit: 'day',
        durationSeconds: '8', durationUnit: 'seconds',
        intensityRating: 'Severe',
        antecedents: 'Item or activity removal, activity transitions, demand presentation, unstructured waiting periods',
        primaryTargets: ['Self'],
        hypothesizedFunction: 'Automatic',
        baselineFrequency: '6',
        targetFrequency: '1',
        measurementSystem: 'Event Recording',
        priorFBACompleted: false,
        priorBIPCompleted: false,
        notes: 'FCT replacement: Functional Requesting (Mand Training) — teaching Emma to exchange a PECS card or activate Proloquo2Go to request a preferred item or "break" eliminates the communicative escape function driving this SIB. See Skill Acquisitions: "Functional Requesting (Mand Training)." Automatic/sensory component will be addressed in parallel via sensory diet (OT) and competing preferred stimulation. Family must honor the mand BEFORE SIB occurs to build the replacement behavior; demand removal following SIB should be avoided.',
      },
      {
        id: 'bt-emma-2',
        behaviorName: 'Tantrum / Drop',
        operationalDefinition: 'Emma cries, screams, and goes limp on the floor, refusing to walk or follow direction. Behavior is considered to begin when Emma drops to the floor and ends when she stands and resumes movement independently.',
        topography: ['Crying/screaming', 'Drop/go limp', 'Refusal to move'],
        frequencyPerDay: '4', frequencyUnit: 'day',
        durationSeconds: '10', durationUnit: 'minutes',
        intensityRating: 'Moderate',
        antecedents: 'Departure cues (shoes, jacket, bag), leaving a preferred activity, caregiver verbal instruction to transition',
        primaryTargets: ['Parent'],
        hypothesizedFunction: 'Escape',
        baselineFrequency: '4',
        targetFrequency: '1',
        measurementSystem: 'Duration Recording',
        priorFBACompleted: false,
        priorBIPCompleted: false,
        notes: 'Two-pronged skills approach: (1) Functional Requesting (Mand Training) teaches Emma to request a break or "all done" via PECS/AAC before dropping — directly replaces the escape function. (2) Transition Tolerance (First-Then Compliance) skill goal builds gradual tolerance for high-frequency transitions (iPad → meal, play → departure) using visual First-Then cues and countdown timers. Family must stop offering preferred items during tantrum/drop episodes as this reinforces both escape and access functions simultaneously.',
      },
    ],
  },
  crisis_plan: {
    notes: 'No prior crisis events, hospitalizations, or law enforcement involvement. Suicidal ideation cannot be directly assessed given communication level — monitor behavioral indicators closely. Communication level precludes verbal expression of distress. Deep pressure (firm hug) effective ~60% per mom report — must be offered, not imposed. Return to baseline: 10–20 min. No medical contraindications. Caregiver has reviewed and signed crisis plan.',
    transcript: "Mom: When she's heading toward a real meltdown there are signs — she starts rocking faster and the flapping gets more intense. And then the crying starts. We take everything away, dim the lights if we can, and we just wait. If she lets us, a firm hug helps. But if we try to block her or talk too much, it's worse. It's never gotten to a point where we needed to call anyone. Dad: She usually calms down within 10 or 15 minutes if we give her space. Then she kind of collapses and wants to cuddle. That's how we know it's over.",
    completionState: 'complete',
    emergencyContacts: [
      { id: 'ec-e1', name: 'Linda Thompson', relationship: 'Mother', phone: '(561) 555-0167', role: 'Primary' },
      { id: 'ec-e2', name: 'David Thompson', relationship: 'Father', phone: '(561) 555-0168', role: 'Backup' },
      { id: 'ec-e3', name: 'Dr. Sarah Mills', relationship: 'Pediatrician', phone: '(561) 555-0200', role: 'Medical' },
    ],
    warningSignsSelected: [
      'Rocking speed increase',
      'Bilateral hand flapping (intensified)',
      'Elevated vocal volume',
      'Crying onset',
    ],
    warningSignsCustom: 'Sustained whining that escalates in pitch; repeated hand-leading toward door (elopement attempt precursor).',
    deEscalationWorks: [
      'Remove all demands',
      'Dim lights',
      'Wait quietly — no talking',
      'Deep pressure / firm hug',
      'Offer chew / fidget tool',
    ],
    deEscalationWorsens: [
      'Physical blocking or restraint',
      'Multiple verbal prompts in sequence',
      'Removing preferred items',
      'Raised voice / urgent tone',
    ],
    deEscalationNotes: 'Deep pressure (firm squeeze hug) is effective approximately 60% of the time per parent report — must be offered, never imposed. Mom is more effective than dad at initiating. Offer chew necklace before meltdown escalates to SIB window.',
    bcbaCallMinutes: '5',
    bcbaCallIncidents: '3',
    bcbaCallWindow: '20',
    call911Threshold: true,
    call911Notes: 'Any SIB resulting in visible bleeding or injury requiring medical attention. Loss of consciousness of any duration.',
    sessionSuspendThreshold: false,
    baselineReturnMin: '10',
    baselineReturnMax: '20',
    postCrisisDebrief: true,
    remorsePresentPostCrisis: false,
    medicalContraindications: ['No physical blocking', 'No physical restraint of any kind'],
    medicalNotes: 'No current medications. No allergies. Seizure history negative. Deep pressure can be used as de-escalation tool with caregiver guidance.',
    caregiverSignedCrisisPlan: true,
    rbtTrainedOnPlan: false,
    crisisPlanInBsp: true,
  },
};

// ── Marcus Rivera mock data ──────────────────────────────────────────────────

const MARCUS_INTERVIEW_DATA = {
  demographics: {
    notes: 'Marcus Rivera, DOB 03/04/2017 (age 9). Dx: ASD Level 2 F84.0 + ADHD Combined F90.2 + GAD F41.1 (Dr. Elena Vargas Psy.D., Jan 2024 — ADOS-2 Module 3, ADI-R, Vineland-3). Insurance: Florida Blue FLB-774421 / G-12390; Medicaid secondary FL-MCD-88221. Lives with parents Daniela + Javier Rivera + sister Sofia (age 6, NT). Spanish spoken by maternal grandparents (afterschool care 3x/week). School: Sunset Elementary, Miami-Dade, 3rd grade — IEP (re-eval Feb 2025), 1:1 aide full-day, SLP 30 min/week, OT 60 min/week. Prior ABA: Sunshine Behavioral Health Oct 2022–Jun 2023, 15 hr/week center (discontinued on relocation). Meds: Guanfacine ER 1mg QD (Dr. Adriana Costa).',
    completionState: 'complete',
  },
  presenting_concerns: {
    notes: 'Family top 3 concerns: (1) Physical aggression toward mom + sister — 3-7 incidents/day, includes hitting, object throwing, and 2 biting incidents past 60 days. Onset worsened Oct 2025 when school paraprofessional reassigned. (2) Regression in bathing — independent at age 7, now refuses completely. 45-60 min standoffs at bathroom door daily. (3) Severe community anxiety — family has avoided restaurants, grocery stores, extended family events for ~4 months. School: 2 documented peer aggression incidents, 1 in-school suspension. IEP team considering placement review.',
    transcript: "Mom: It escalated a lot around October last year when his aide changed at school. That seemed to really destabilize him. And then the hitting at home went from occasional to every single day. He bit me hard enough to leave bruises — twice. And I can't get him in the bath at all now. He used to do it by himself. Something shifted. We've basically stopped going out as a family because I genuinely can't predict what will happen in a store or a restaurant. Dad: At school they've documented two incidents with other kids hitting and he got suspended once. We're worried about his placement.",
    completionState: 'complete',
  },
  self_help: {
    notes: 'Toileting: fully independent, no concerns. Dressing: independent for pullover tops and elastic-waist bottoms. Buttons/snaps require prompting and frequently refused. Shoelaces not mastered — Velcro/slip-on exclusively. Tolerates tooth brushing with verbal prompt. Refuses flossing. Hair combing with minimal prompt. Face washing: ~50% mornings. Bathing: significant regression — was independent at age 7, now refuses bathing entirely. 45-60 min standoffs. Sponge bath used as temporary accommodation. Tactile sensitivity: tagless shirts required, refuses jeans/stiff fabric, limiting wardrobe. Feeding: 12-14 accepted foods — all smooth/mild texture or familiar brand. Chicken nuggets (specific brand), plain pasta, white rice, peeled apple slices, graham crackers, yogurt pouches. No vegetables accepted. OT feeding eval Jan 2025: sensory-based avoidance + conditioned aversion component.',
    completionState: 'partial',
  },
  daily_living: {
    notes: 'Morning routine: visual schedule in use (laminated, bedroom wall) — works ~80% when preferred parent present, drops to ~40% when that parent unavailable. Routine currently 55-70 min; family goal is 30 min. Bedtime: ~90% adherence when started by 8pm. Delayed start results in behavioral escalation. Sleep: no difficulties once routine initiated. Chores: none completed independently. Can carry plate to sink with prompt. Community outings: largely suspended past 4 months (see Presenting Concerns). Prior to regression: managed familiar settings (library, playground, family restaurant). Street safety intact — responds appropriately to crossing cues. Personal safety info: knows full name, home address, caregiver phone numbers. Leisure: LEGO (advanced instruction builds, up to 45 min independent), YouTube (trains/science), backyard trampoline. Screen time: 4-6 hrs/day weekends, unregulated.',
    completionState: 'partial',
  },
  safety: {
    notes: 'Elopement: no history. Pool: above-ground backyard pool, locked gate, supervised only — no unsupervised access reported. SIB: self-hitting (hand to head/face) during severe escalation, 3-5x/week, brief (<30 sec), no medical attention required. Part of escalation sequence. Aggression (PRIMARY CONCERN): open-hand hitting (70% of incidents), object throwing (1-2x/week), biting (2 incidents past 60 days). Targets: mom 60%, sister 30%, school peers (2 documented). No injuries requiring medical care. Visible bruising on mom from biting. No law enforcement. Property destruction: minimal — occasional surface sweep of small items, no sustained destruction. Home: structured, safe, appropriate for ABA delivery.',
    transcript: "He has never tried to run away. The main safety concern in the home is the hitting and the biting. The two biting incidents — he bit me hard enough to leave bruises that lasted almost a week. Both times I had tried to physically redirect him during a severe meltdown, which I now know makes it worse. He's never injured his sister badly but she's frightened of him and avoids him. We have a pool in the backyard but the gate is always locked and he's never tried to go near it unsupervised. No law enforcement, no hospitalizations — nothing like that.",
    completionState: 'complete',
    riskLevel: 'High',
    sibPresent: true,
    sibTopography: ['Face slapping'],
    sibFrequency: '2',
    sibInjuryHistory: false,
    sibInjuryNotes: 'Self-hitting (hand to head/face) occurs during peak escalation, 3-5x/week, episodes brief (<30 sec). No medical attention required. Part of escalation sequence, not a standalone behavior.',
    aggressionPresent: true,
    aggressionTopography: ['Open-hand hitting', 'Biting', 'Object throwing'],
    aggressionTargets: ['Parent / Caregiver', 'Sibling', 'Peers'],
    aggressionFrequency: '5',
    aggressionInjuryHistory: true,
    aggressionInjuryNotes: '2 biting incidents in past 60 days — both directed at mom during physical redirection. Bruising documented lasting ~1 week. 2 school incidents involving peer hitting (1 in-school suspension). No ER visits or medical treatment required.',
    elopementPresent: false,
    propertyDestructionPresent: true,
    propertyDestructionNotes: 'Occasional surface sweep of small items during escalation. No sustained or targeted destruction. No significant property damage reported.',
    envSafety: [
      'Pool / water body secured or no access',
      'Firearms secured or not present',
      'Medications stored out of reach',
    ],
    lawEnforcementInvolvement: false,
    hospitalizationHistory: false,
  },
  communication: {
    notes: 'Verbal — MLU 6-8 words familiar context, shorter under stress. Intelligibility ~90% familiar, 60-70% upset. Uses language to request, protest, comment (trains/science topics), factual questions. Critical gap: does not use language to express internal emotional states, negotiate, or ask for help before escalating. Delayed echolalia (YouTube quotes) during unstructured time/anxiety — regulatory function; immediate echolalia not present. Receptive: multi-step in familiar contexts; drops significantly in novel/anxious settings. Consistent name response with familiar adults. Yes/no reliable. Multi-person instructions inconsistent with strangers. Pragmatics: initiates with adults on preferred topics; peer initiation limited (factual sharing only). Turn-taking 3-4 exchanges preferred topic. Non-literal language (sarcasm, idioms) not understood. Current SLP: Ms. Daniela Cruz (30 min/week, pragmatics and social communication).',
    transcript: "Mom: He talks — a lot actually, when it's about trains or something he's interested in. Full sentences, back and forth, very clear. But the moment something frustrates him or something goes wrong, the language disappears. He doesn't say 'I'm upset' or 'I need help' — he just explodes. It's like the words aren't available to him anymore in those moments. Dad: He can follow instructions when things are calm and he's in a good place. But when he's anxious or we're in a new place, he goes blank — he won't respond even to his name sometimes. Mom: The SLP says he needs to learn to use language to self-advocate in those hard moments, but it's only 30 minutes a week and we can't figure out how to practice it at home without it turning into a fight.",
    completionState: 'complete',
    primaryCommunicationModes: ['Verbal'],
    mluWords: '7',
    intelligibilityFamiliar: '90',
    intelligibilityUnfamiliar: '65',
    functionalRepertoire: [
      'Requesting preferred items/activities',
      'Protesting / refusing',
      'Commenting / sharing information',
      'Greeting familiar people',
      'Answering yes/no questions',
      'Labeling objects/actions',
    ],
    receptiveSingleStep: '90',
    receptiveTwoStep: '70',
    receptiveMultiStep: false,
    eyeContact: 'Variable',
    initiatesCommunication: 'Sometimes',
    turnTaking: 'Present',
    slpServices: true,
    slpFrequencyPerWeek: '1',
    slpFocus: 'Pragmatics and social communication',
  },
  self_stim: {
    notes: 'Hand flapping: highest frequency — 20-30 episodes/day, excitement/anticipation/transitions. Episodes 5-30 sec. Stigmatizing at school — peer teasing reported. Rocking while seated: during tasks and screen time, occasionally disrupts attention. Verbal scripting (delayed echolalia): YouTube content during unstructured time/anxiety; extended periods reported as distressing to family. Repetitive reading of train timetables/maps — regulatory/calming function. Sensory profile: hyperreactivity to unexpected sounds (hand dryers, fire alarms, crowds), tactile defensiveness specific fabrics, mild visual sensitivity to fluorescent environments (school cafeteria). OT eval Jan 2025: sensory modulation difficulties, mixed hyper/hyposensitivity. Proprioceptive seeking also noted. Accommodations: noise-canceling headphones, weighted lap pad, fidget tools at school.',
    completionState: 'partial',
  },
  medical_necessity: {
    notes: 'Dx: ASD Level 2 F84.0, ADOS-2 Module 3 + ADI-R + Vineland-3 (Dr. Vargas, Jan 2024). Co-occurring: ADHD Combined F90.2 + GAD F41.1 (Dr. Costa, March 2025). Meds: Guanfacine ER 1mg QD — no acute behavioral effects. No seizures, cardiac conditions, or treatment contraindications. Daily aggression threatening caregiver and sibling safety. ADL regression (bathing) is clinically significant — previously mastered skill lost. Severe food restriction limiting nutritional variety and community participation. Morning routine failures causing school tardiness. School aggression — potential restrictive placement change. Prior ABA: beneficial per caregiver, regression followed discontinuation — supports reauthorization rationale. Without ABA: worsening trajectory, school placement at risk, community participation eliminated. Recommend: 20-25 hrs/week given severity, functioning, prior partial response, and family engagement.',
    transcript: "Mom: He was diagnosed in January 2024 by Dr. Vargas — she did the full psychological evaluation. Then about a year later, Dr. Costa added the ADHD and anxiety diagnoses. He's been on Guanfacine since March for the ADHD and attention — it takes the edge off a little but we haven't seen a big change in the aggression. He did ABA before, from late 2022 to mid-2023 at Sunshine Behavioral. It was working. He was calmer, the behaviors were less frequent, we had strategies. And then we relocated and had to stop. Within a few months he regressed back to where he was before and then kept getting worse. That regression is the thing that makes us feel like ABA is absolutely necessary. Dr. Costa and Dr. Vargas both wrote letters of support for this referral. Dad: Without this we are genuinely worried about whether we can keep our family safe.",
    completionState: 'complete',
    coOccurringDiagnoses: [
      { id: 'dx-m1', diagnosis: 'ADHD Combined Type', icd10: 'F90.2', provider: 'Dr. Elena Vargas, Psy.D.', date: 'Jan 2024' },
      { id: 'dx-m2', diagnosis: 'Generalized Anxiety Disorder', icd10: 'F41.1', provider: 'Dr. Adriana Costa', date: 'Mar 2025' },
    ],
    medications: [
      { id: 'med-m1', name: 'Guanfacine ER', dose: '1mg', frequency: 'QD (morning)', prescriber: 'Dr. Adriana Costa', purpose: 'ADHD / attention regulation' },
    ],
    hasPriorABA: true,
    priorABAHistory: [
      { id: 'aba-m1', provider: 'Sunshine Behavioral Health', startDate: 'Oct 2022', endDate: 'Jun 2023', hoursPerWeek: '15', setting: 'Center-based', reasonDiscontinued: 'Family relocation' },
    ],
    recommendedHoursPerWeek: '22',
    recommendedSetting: 'Center-based',
  },
  skill_acquisitions: {
    notes: 'Family priority targets: (1) Functional help-seeking and break-requesting verbally before escalating — critical safety target; (2) morning routine independence, full 8-step within 30 min; (3) peer interaction initiation at school. Academic: 3rd grade content, difficulty with multi-step word problems and written expression. Attention 15-20 min with 1:1 support. Social: no peer friendships. Parallel play in structured settings. No spontaneous peer initiation. Joint attention present but limited. Theory of mind emerging, inconsistent. No social skills group history. Imitation: action imitation strong, vocal imitation moderate. Reinforcers identified: LEGO sets (specific), YouTube access (trains/science), chips/crunchy snacks, trampoline time, computer time.',
    completionState: 'complete',
    skillGoals: [
      {
        id: 'mg1',
        targetSkill: 'Functional Help-Seeking (Verbal Request)',
        operationalDefinition: 'Marcus independently vocalizes a contextually appropriate help-seeking statement ("I need help," "Can you help me?", or "I don\'t know how to do this") within 10 seconds of encountering a task difficulty or blocked access, without adult prompting.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Discrete Trial Training (DTT)', 'Natural Environment Teaching (NET)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Verbal', promptingLevelCombination: '',
        baselinePercent: '5', baselineOpportunities: '20',
        baselinePromptingDesc: 'Full verbal model required; unprompted help-seeking absent across all probe settings — Marcus escalates to aggression instead',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '3',
        masteryCriteriaSettings: 'Home + school + at least 1 community setting',
        masteryCriteriaPrompting: 'Independent — no verbal or gestural prompt',
        generalizationNotes: 'Generalize across caregivers, RBT, teacher, and paraprofessional. Probe across task types: academic, self-care, play, and blocked access. Priority probe antecedents match the Physical Aggression behavior target: ending preferred activity (tablet, LEGO), grooming demands, sibling disruption, post-school transitions. Reduction in Physical Aggression frequency serves as the primary real-world measure of skill generalization.',
      },
      {
        id: 'mg2',
        targetSkill: 'Morning Routine Completion (Independent Sequencing)',
        operationalDefinition: 'Marcus completes all 8 steps of the morning routine in correct sequence within 30 minutes using a visual schedule independently, with no more than 1 verbal prompt total per routine.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Task Analysis / Chaining', 'Discrete Trial Training (DTT)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Verbal', promptingLevelCombination: '',
        baselinePercent: '38', baselineOpportunities: '8',
        baselinePromptingDesc: 'Completes 3 of 8 steps independently with primary caregiver; 4-6 verbal prompts required; routine averages 55-70 minutes',
        masteryCriteriaPercent: '100', masteryCriteriaSessions: '5',
        masteryCriteriaSettings: 'Home — must meet criterion with both parents as routine leader',
        masteryCriteriaPrompting: 'Independent (no more than 1 total verbal prompt per routine)',
        generalizationNotes: 'The 8 routine steps include: (1) wake up/out of bed, (2) toilet, (3) brush teeth, (4) wash face, (5) bathing — highest resistance step, addressed concurrently via Bathing/Grooming Desensitization skill goal, (6) get dressed, (7) breakfast, (8) backpack ready. Probe weekend routine. Address holiday/schedule-change disruption with advance visual priming. Fade laminated schedule to checklist, then internalized. Full routine completion with bathing included (not sponge bath accommodation) is the mastery criterion.',
      },
      {
        id: 'mg3',
        targetSkill: 'Peer Interaction Initiation (School Setting)',
        operationalDefinition: 'Marcus independently initiates a non-scripted, contextually appropriate social interaction with a same-age peer (e.g., commenting on shared activity, requesting to join a game, offering a compliment) at least 2 times per 30-minute structured social opportunity, without adult prompting.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Social Stories', 'Video Modeling', 'Peer-Mediated Instruction', 'Natural Environment Teaching (NET)'],
        teachingStrategiesOther: '',
        promptingLevel: 'Gestural', promptingLevelCombination: '',
        baselinePercent: '0', baselineOpportunities: '10',
        baselinePromptingDesc: 'Zero unprompted peer initiations observed across 3 observation sessions; all peer contact is reactive, not initiated',
        masteryCriteriaPercent: '80', masteryCriteriaSessions: '5',
        masteryCriteriaSettings: 'School recess + classroom cooperative tasks',
        masteryCriteriaPrompting: 'Independent — no verbal or gestural prompt',
        generalizationNotes: 'Community generalization (playground, library events) after school mastery achieved. Family-arranged structured playdates as natural environment probe.',
      },
      {
        id: 'mg4',
        targetSkill: 'Bathing / Grooming Desensitization',
        operationalDefinition: 'Marcus completes the full bathing sequence (enter bathroom, undress, enter shower/tub, tolerate water contact for minimum 5 minutes, wash hair with shampoo, rinse, exit, dry) without verbal refusal, physical resistance, or dropping, when provided with a visual step sequence and a 2-minute advance warning.',
        definitionIsAiGenerated: false, definitionIsLoading: false,
        teachingStrategies: ['Task Analysis / Chaining', 'Natural Environment Teaching (NET)'],
        teachingStrategiesOther: 'Systematic desensitization with gradual water exposure hierarchy',
        promptingLevel: 'Verbal', promptingLevelCombination: '',
        baselinePercent: '0', baselineOpportunities: '7',
        baselinePromptingDesc: 'Zero independent bathing completions in past 7 days; 45-60 min refusal episode every evening; sponge bath used as accommodation. Was independent at age 7.',
        masteryCriteriaPercent: '100', masteryCriteriaSessions: '10',
        masteryCriteriaSettings: 'Home — both parents as routine leader across consecutive evenings',
        masteryCriteriaPrompting: 'Visual step sequence + 2-minute advance warning only; no additional verbal or physical prompt',
        generalizationNotes: 'Coordinate with OT re: sensory desensitization hierarchy for water temperature (warm preferred) and hair washing (handheld showerhead, no direct overhead spray). Embed bathing as Step 5 of Morning Routine Completion goal sequence once achieved independently in evening context. Reduction in Bathing Refusal behavior target (currently 45-60 min/night) is the direct clinical outcome measure. Marcus may use Functional Help-Seeking ("I need a minute") during steps — honor immediately to build trust and prevent escalation.',
      },
    ],
  },
  behavior_targets: {
    notes: 'Target 1: Physical Aggression. Topography: open-hand hitting 70%, object throwing ~1-2x/week, biting 2 incidents/60 days. Frequency: 3-7x/day. Targets: mom 60%, sister 30%, school peers 2 documented. Ant: ending preferred activity (tablet/LEGO), grooming demands, sibling disruption of preferred activity, schedule change. Highest occurrence: weekday post-school decompression period. Function: escape (primary) — demand consistently removed post-aggression. Attention secondary for sibling incidents. Target 2: Bathing refusal. Topography: verbal refusal, physical resistance at bathroom doorway, dropping/going limp, crying/screaming. Duration: 45-60 min. Daily. Ant: verbal cue that bath time is starting. Function: escape sensory-aversive grooming task. No prior FBA. No BIP in place.',
    transcript: "Post-school is the highest risk time. He gets off the bus, he's done, and if anyone asks anything of him or his sister interrupts his LEGO it escalates fast. I've learned to give transition warnings but it doesn't always work. The biting — that was only me, only during really severe meltdowns when I tried to physically intervene. Both times I was left with bruises that lasted almost a week. I feel like I've started to be afraid of my own child and that feeling is really hard to sit with. The bath is every single night. He stands outside the bathroom door and we go back and forth sometimes for an hour.",
    completionState: 'complete',
    behaviorTargets: [
      {
        id: 'bt-marcus-1',
        behaviorName: 'Physical Aggression',
        operationalDefinition: 'Marcus makes forceful physical contact with another person or throws an object in the direction of a person. Includes open-hand hitting, biting (skin contact with teeth), and object throwing within 3 feet of a person. Each discrete contact or throw counts as one instance.',
        topography: ['Open-hand hitting', 'Biting', 'Object throwing'],
        frequencyPerDay: '5', frequencyUnit: 'day',
        durationSeconds: '10', durationUnit: 'seconds',
        intensityRating: 'Severe',
        antecedents: 'Ending preferred activity (tablet, LEGO), grooming demands, sibling disruption of preferred activity, schedule change, post-school transitions',
        primaryTargets: ['Parent', 'Sibling', 'Peers'],
        hypothesizedFunction: 'Escape',
        baselineFrequency: '5',
        targetFrequency: '0',
        measurementSystem: 'Event Recording',
        priorFBACompleted: false,
        priorBIPCompleted: false,
        notes: 'FCT replacement: Functional Help-Seeking (Verbal Request) — Marcus learns to vocalize "I need help," "I need a break," or "I need a minute" BEFORE escalating to physical contact. Treatment plan pairs FCT skill acquisition (see Skill Acquisitions: "Functional Help-Seeking") with extinction of aggression + DRA reinforcing verbal requests. Attention-maintained sibling-directed incidents addressed via differential reinforcement of sibling proximity tolerance. CRITICAL caregiver guidance: do NOT remove the demand following aggression — prompt the verbal help-seeking response instead and immediately honor it. 2 biting incidents in past 60 days involved mom during physical intervention; avoid restraint during peak escalation.',
      },
      {
        id: 'bt-marcus-2',
        behaviorName: 'Bathing Refusal',
        operationalDefinition: 'Marcus verbally refuses, physically resists at the bathroom doorway, drops to the floor, or cries/screams in response to a bathing cue. Episode begins at the first verbal refusal or physical resistance and ends when Marcus enters the bathroom and begins the bathing routine without further protest.',
        topography: ['Verbal refusal', 'Drop/go limp', 'Crying/screaming', 'Physical resistance'],
        frequencyPerDay: '1', frequencyUnit: 'day',
        durationSeconds: '50', durationUnit: 'minutes',
        intensityRating: 'Moderate',
        antecedents: 'Verbal cue that bath time is starting, proximity to bathroom, visual cue (towel, caregiver movement toward bathroom)',
        primaryTargets: ['Parent'],
        hypothesizedFunction: 'Escape',
        baselineFrequency: '1',
        targetFrequency: '0',
        measurementSystem: 'Duration Recording',
        priorFBACompleted: false,
        priorBIPCompleted: false,
        notes: 'Skill-based dual approach: (1) Morning Routine Completion goal (see Skill Acquisitions) includes bathing as Step 5 of the 8-step visual schedule — systematic desensitization embedded within the routine using backward chaining (enter bathroom → water-only contact → partial bath → full routine). (2) Bathing/Grooming Desensitization skill goal targets sensory tolerance for water temperature and hair washing specifically. FCT overlap: Marcus may use Functional Help-Seeking to request "a minute" during bathing steps — this is reinforced as appropriate self-advocacy. Regression correlates with schedule disruption Oct 2025; consistent schedule restoration is prerequisite intervention. Parent training critical: reinforce each sub-step entered, avoid extended negotiations at bathroom doorway.',
      },
    ],
  },
  crisis_plan: {
    notes: 'No prior hospitalization, psychiatric crisis, or law enforcement involvement. No suicidal ideation beyond described SIB. No prior formal crisis plan in place — this is first documented plan. Escalation sequence: warning signs → verbal protest → motor agitation → crying/screaming → physical aggression → occasional SIB. Post-episode: Marcus frequently initiates affection and apologizes verbally — remorse awareness confirmed. Guanfacine ER 1mg QD — no acute behavioral effects documented; no contraindications for de-escalation strategies. Physical redirection during escalation has precipitated 2 biting incidents.',
    transcript: "Mom: When it's starting you can see it — he starts pacing and the echolalia gets louder. He'll repeat things more and more and won't make eye contact. Then it goes to verbal protest and then full meltdown. What I've learned is that if I give him the tablet for 5 minutes in a quiet space — no talking, just one simple instruction — he can come back. But if I try to physically redirect him or if his sister comes near during that window, it escalates immediately. He bit me twice when I tried to physically guide him during a crisis. After the meltdown he usually cries and apologizes and wants to hug me. Dad: We don't have any formal plan written anywhere. Nobody gave us one. That's partly why we're here.",
    completionState: 'complete',
    emergencyContacts: [
      { id: 'ec-m1', name: 'Daniela Rivera', relationship: 'Mother', phone: '(305) 555-0302', role: 'Primary' },
      { id: 'ec-m2', name: 'Javier Rivera', relationship: 'Father', phone: '(305) 555-0303', role: 'Backup' },
      { id: 'ec-m3', name: 'Dr. Adriana Costa', relationship: 'Prescribing Physician', phone: '(305) 555-0410', role: 'Medical' },
    ],
    warningSignsSelected: [
      'Increased pacing',
      'Elevated vocal volume',
      'Rising echolalia frequency',
      'Refusal of eye contact / body turned away',
      'Repetitive "no" or vocal protest',
      'Bilateral hand flapping (intensified)',
    ],
    warningSignsCustom: 'Delayed echolalia shifts to more urgent, repetitive phrasing. Marcus will refuse to enter the room where the demand was placed.',
    deEscalationWorks: [
      'Move to quiet low-stimulation space',
      'Offer tablet / screen access',
      'Wait quietly — no talking',
      'Single simple statement only',
      'Remove all demands',
    ],
    deEscalationWorsens: [
      'Physical blocking or restraint',
      'Physical redirection without warning',
      'Multiple verbal prompts in sequence',
      'Extended verbal explanations',
      'Sibling / peer proximity during episode',
      'Raised voice / urgent tone',
    ],
    deEscalationNotes: 'Physical redirection has directly precipitated the 2 documented biting incidents. RBT must never make physical contact during escalation without explicit parent authorization and BCBA guidance. Sibling (Sofia, age 6) must be removed from the area immediately when Marcus enters warning sign phase.',
    bcbaCallMinutes: '7',
    bcbaCallIncidents: '2',
    bcbaCallWindow: '30',
    call911Threshold: true,
    call911Notes: 'Any aggression resulting in injury requiring medical attention. Any self-injurious behavior sustained beyond 2 minutes or resulting in visible skin damage.',
    sessionSuspendThreshold: true,
    sessionSuspendNotes: 'If Marcus initiates biting or object-throwing directed at the RBT, the RBT should calmly move out of range and contact the supervising BCBA immediately. Do not re-engage until BCBA advises.',
    baselineReturnMin: '20',
    baselineReturnMax: '40',
    postCrisisDebrief: true,
    remorsePresentPostCrisis: true,
    remorseNotes: 'Marcus typically initiates verbal apology and physical affection (hug) within 5–10 minutes of returning to baseline. This is a reliable indicator that the episode has fully resolved. Do not attempt to process the event verbally with Marcus during the remorse window — keep it brief and warm.',
    medicalContraindications: ['No physical blocking', 'No physical restraint of any kind'],
    medicalNotes: 'Guanfacine ER 1mg QD (Dr. Adriana Costa) — administered in the morning. No acute behavioral side effects documented. No allergies. No seizure history. Medication does not affect crisis response protocol.',
    caregiverSignedCrisisPlan: false,
    rbtTrainedOnPlan: false,
    crisisPlanInBsp: true,
  },
};

export const SEED_CLIENTS = () => [
  { id:'c1',  name:'Liam Rodriguez',  dob:'2018-03-15', phone:'(786) 555-0121', address:'1432 SW 8th St, Miami, FL 33135',          insurer_name:'Aetna',        member_id:'AET-884421', group_number:'G-44210', referring_provider:'Dr. Maria Santos',  source:'imported',    referral_date:'2026-04-10', stage:'intake',          denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c2',  name:'Sophia Kim',      dob:'2019-07-22', phone:'(305) 555-0198', address:'7821 N Kendall Dr, Miami, FL 33156',        insurer_name:'UnitedHealth', member_id:'UHC-229934', group_number:'G-77811', referring_provider:'Dr. John Park',      source:'crm_created', referral_date:'2026-04-15', stage:'intake',          denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c3',  name:'Noah Carter',     dob:'2017-11-08', phone:'(954) 555-0143', address:'3201 Coral Way, Coral Gables, FL 33134',   insurer_name:'Florida Blue', member_id:'FLB-558871', group_number:'G-12390', referring_provider:'Dr. Elaine Torres',  source:'imported',    referral_date:'2026-03-28', stage:'auth_assessment', denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c4',  name:'Emma Thompson',   dob:'2020-01-30', phone:'(561) 555-0167', address:'9400 Glades Rd, Boca Raton, FL 33434',     insurer_name:'Humana',       member_id:'HUM-334490', group_number:'G-98712', referring_provider:'Dr. Robert Chen',    source:'crm_created', referral_date:'2026-04-02', stage:'assessment',      denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c5',  name:'Oliver Patel',    dob:'2018-06-12', phone:'(786) 555-0134', address:'2100 Biscayne Blvd, Miami, FL 33137',      insurer_name:'Cigna',        member_id:'CIG-778823', group_number:'G-55023', referring_provider:'Dr. Ana Flores',     source:'imported',    referral_date:'2026-03-15', stage:'plan_draft',      denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c6',  name:'Ava Nguyen',      dob:'2019-09-05', phone:'(305) 555-0189', address:'5540 NW 7th Ave, Miami, FL 33127',         insurer_name:'Aetna',        member_id:'AET-991102', group_number:'G-44210', referring_provider:'Dr. Luis Mendez',    source:'crm_created', referral_date:'2026-02-28', stage:'submitted',       denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c7',  name:'Ethan Williams',  dob:'2017-04-18', phone:'(954) 555-0156', address:'800 E Broward Blvd, Ft. Lauderdale, FL',   insurer_name:'Florida Blue', member_id:'FLB-447721', group_number:'G-12390', referring_provider:'Dr. Sarah Johnson',  source:'imported',    referral_date:'2026-02-10', stage:'denied',          denial_reason:'Medical necessity not established', bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c8',  name:'Isabella Moore',  dob:'2018-12-25', phone:'(786) 555-0177', address:'6100 SW 57th Ave, South Miami, FL 33143',  insurer_name:'UnitedHealth', member_id:'UHC-883312', group_number:'G-77811', referring_provider:'Dr. Mark Davis',     source:'crm_created', referral_date:'2026-01-20', stage:'authorized',      denial_reason:null,                         bcba_id:'u2', rbt_id:'u4', auth_expiry_date:'2026-12-31', reauth_active:false },
  { id:'c9',  name:'Mason Garcia',    dob:'2019-03-14', phone:'(305) 555-0145', address:'11200 SW 8th St, Miami, FL 33174',         insurer_name:'Humana',       member_id:'HUM-229908', group_number:'G-98712', referring_provider:'Dr. Patricia Lee',   source:'imported',    referral_date:'2026-01-05', stage:'staffing',        denial_reason:null,                         bcba_id:'u2', rbt_id:'u4', auth_expiry_date:'2026-12-15', reauth_active:false },
  { id:'c10', name:'Charlotte Davis', dob:'2018-08-22', phone:'(561) 555-0122', address:'3400 PGA Blvd, Palm Beach Gardens, FL',    insurer_name:'Cigna',        member_id:'CIG-556634', group_number:'G-55023', referring_provider:'Dr. James Wilson',   source:'crm_created', referral_date:'2025-11-12', stage:'services',        denial_reason:null,                         bcba_id:'u2', rbt_id:'u4', auth_expiry_date:'2026-05-27', reauth_active:true  },
  { id:'c11', name:'James Martinez',  dob:'2017-05-30', phone:'(786) 555-0190', address:'1800 Coral Way, Miami, FL 33145',          insurer_name:'Aetna',        member_id:'AET-664433', group_number:'G-44210', referring_provider:'Dr. Angela Rivera',  source:'imported',    referral_date:'2025-10-08', stage:'services',        denial_reason:null,                         bcba_id:'s1', rbt_id:'s5', auth_expiry_date:'2026-05-20', reauth_active:true  },
  { id:'c12', name:'Amelia Wilson',   dob:'2020-02-14', phone:'(954) 555-0133', address:'2800 Hollywood Blvd, Hollywood, FL 33020', insurer_name:'Florida Blue', member_id:'FLB-112298', group_number:'G-12390', referring_provider:'Dr. Kevin Brown',    source:'crm_created', referral_date:'2026-03-01', stage:'auth_assessment', denial_reason:null,                         bcba_id:'s2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
  { id:'c13', name:'Marcus Rivera',  dob:'2017-03-04', phone:'(305) 555-0302', address:'4820 SW 137th Ave, Miami, FL 33175',         insurer_name:'Florida Blue', member_id:'FLB-774421', group_number:'G-12390', referring_provider:'Dr. Adriana Costa',  source:'imported',    referral_date:'2026-05-01', stage:'assessment',      denial_reason:null,                         bcba_id:'u2', rbt_id:null, auth_expiry_date:null,        reauth_active:false },
].map(c => {
  const cl = mkChecklist();
  // Pre-complete c7 (Ethan Williams) denied checklist so resolve button is enabled
  if (c.id === 'c7') {
    cl.denied.denial_reason = 'Medical necessity not established';
    cl.denied.peer_to_peer_scheduled = true;
    cl.denied.supporting_docs = true;
    cl.denied.peer_to_peer_completed = true;
  }

  const SEED_NOTES = {
    c9: [
      { id:'n9b', stage:'staffing',  text:'RBT confirmed availability for 3x/week sessions starting next Monday. Parent agreed to morning slot.', author:'Tanya Reyes', timestamp:'2026-05-18T09:15:00Z' },
      { id:'n9a', stage:'authorized', text:'Called caregiver, left voicemail re: schedule change for upcoming assessment week.', author:'Dr. Priya Sharma', timestamp:'2026-05-15T14:32:00Z' },
    ],
    c10: [
      { id:'n10b', stage:'services',  text:'Reauth paperwork submitted to Cigna. Expect decision within 10 business days per rep.', author:'Jordan Ellis', timestamp:'2026-05-19T11:05:00Z' },
      { id:'n10a', stage:'services',  text:'Family reported positive progress with self-regulation goals this month. Updated behavior plan accordingly.', author:'Jordan Ellis', timestamp:'2026-05-12T16:45:00Z' },
    ],
    c11: [
      { id:'n11a', stage:'services',  text:'Discussed session frequency reduction with caregiver — agreed to move from 5x to 4x/week pending reauth approval.', author:'Dr. Rachel Kim', timestamp:'2026-05-17T10:20:00Z' },
    ],
  };

  const assessment_session =
    c.id === 'c4' ? makeFilledSession(c.id, c.name, c.bcba_id, 'Dr. Ana Reyes', EMMA_INTERVIEW_DATA, {
      dob:                c.dob,
      phone:              c.phone,
      address:            c.address,
      insurerName:        c.insurer_name,
      memberId:           c.member_id,
      groupNumber:        c.group_number,
      referringProvider:  c.referring_provider,
      referralDate:       c.referral_date,
      gender:             'Female',
      diagnosis:          'Autism Spectrum Disorder, Level 3',
      icd10:              'F84.0',
      medicaidId:         '',
      assessmentDate:     '2026-05-22',
      assessmentType:     'Initial',
      preferredLanguage:  'English',
      parentGuardianNames:'Linda & David Thompson',
      relationship:       'Parents',
      reasonForReferral:  'ABA evaluation for significant behavioral challenges and communication delays',
    }) :
    c.id === 'c13' ? makeFilledSession(c.id, c.name, c.bcba_id, 'Dr. Ana Reyes', MARCUS_INTERVIEW_DATA, {
      dob:                c.dob,
      phone:              c.phone,
      address:            c.address,
      insurerName:        c.insurer_name,
      memberId:           c.member_id,
      groupNumber:        c.group_number,
      referringProvider:  c.referring_provider,
      referralDate:       c.referral_date,
      gender:             'Male',
      diagnosis:          'Autism Spectrum Disorder, Level 2',
      icd10:              'F84.0',
      medicaidId:         'FL-MCD-88221',
      assessmentDate:     '2026-05-22',
      assessmentType:     'Initial',
      preferredLanguage:  'English',
      parentGuardianNames:'Daniela & Javier Rivera',
      relationship:       'Parents',
      reasonForReferral:  'ABA evaluation for behavioral escalation, ADL regression, and community avoidance',
    }) :
    c.stage === 'assessment' ? makeAssessmentSession(c.id, c.name, c.bcba_id, 'Dr. Ana Reyes') :
    null;

  return { ...c, pipeline_entry:true, smart_assessment_session_id:null, checklist:cl, documents:[], activity_log:[], case_notes: SEED_NOTES[c.id] || [], assessment_session };
});

export const SEED_STAFF = () => [
  { id:'u2',  name:'Dr. Ana Reyes',    initials:'AR', email:'ana@abashield.com',       phone:'(555) 100-0001', role:'bcba', cert_number:'BCBA-223344', cert_expiry:'2027-09-30', status:'active'  },
  { id:'u4',  name:'James Torres',     initials:'JT', email:'james@abashield.com',     phone:'(555) 100-0002', role:'rbt',  cert_number:'RBT-112200',  cert_expiry:'2027-08-15', status:'active'  },
  { id:'s1',  name:'Dr. Rachel Kim',   initials:'RK', email:'r.kim@abashield.com',    phone:'(555) 201-0034', role:'bcba', cert_number:'BCBA-112233', cert_expiry:'2027-06-30', status:'active'  },
  { id:'s2',  name:'Marcus Webb',      initials:'MW', email:'m.webb@abashield.com',   phone:'(555) 304-0187', role:'bcba', cert_number:'BCBA-445566', cert_expiry:'2026-11-15', status:'active'  },
  { id:'s3',  name:'Dr. Priya Sharma', initials:'PS', email:'p.sharma@abashield.com', phone:'(555) 407-0256', role:'bcba', cert_number:'BCBA-778899', cert_expiry:'2027-03-31', status:'active'  },
  { id:'s4',  name:'Jordan Ellis',     initials:'JE', email:'j.ellis@abashield.com',  phone:'(555) 512-0093', role:'bcba', cert_number:'BCBA-334455', cert_expiry:'2026-06-20', status:'active'  },
  { id:'s5',  name:'Tanya Reyes',      initials:'TR', email:'t.reyes@abashield.com',  phone:'(555) 618-0342', role:'rbt',  cert_number:'RBT-881122',  cert_expiry:'2026-12-31', status:'active'  },
  { id:'s6',  name:'Devon Clark',      initials:'DC', email:'d.clark@abashield.com',  phone:'(555) 720-0165', role:'rbt',  cert_number:'RBT-334455',  cert_expiry:'2026-10-15', status:'active'  },
  { id:'s7',  name:'Aaliyah Foster',   initials:'AF', email:'a.foster@abashield.com', phone:'(555) 823-0471', role:'rbt',  cert_number:'RBT-667788',  cert_expiry:'2027-01-28', status:'active'  },
  { id:'s8',  name:'Carlos Mendez',    initials:'CM', email:'c.mendez@abashield.com', phone:'(555) 916-0088', role:'rbt',  cert_number:'RBT-990011',  cert_expiry:'2026-08-10', status:'active'  },
  { id:'s9',  name:'Yuki Tanaka',      initials:'YT', email:'y.tanaka@abashield.com', phone:'(555) 103-0529', role:'rbt',  cert_number:'RBT-223344',  cert_expiry:'2027-04-22', status:'pending' },
  { id:'s10', name:'Brianna Stone',    initials:'BS', email:'b.stone@abashield.com',  phone:'(555) 205-0617', role:'rbt',  cert_number:'RBT-556677',  cert_expiry:'2026-07-05', status:'pending' },
];

export const SEED_USERS = [
  { id:'u1', name:'Admin User',    email:'admin@abashield.com', role:'admin' },
  { id:'u2', name:'Dr. Ana Reyes', email:'ana@abashield.com',   role:'bcba'  },
  { id:'u3', name:'Dr. Sara Kim',  email:'sara@abashield.com',  role:'bcaba' },
  { id:'u4', name:'James Torres',  email:'james@abashield.com', role:'rbt'   },
];
